spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/unisport
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/unisport
          jwk-set-uri: http://localhost:8080/realms/unisport/protocol/openid-connect/certs
server:
  port: 8081
